version: '3.8'
services:
  # Backend: Authentication Service
  authentication-service:
    container_name: authentication-service
    build: ./backend_service/authentication-service
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb

  # Database: PostgreSQL
  postgresdb:
    container_name: postgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=catalogue
    volumes:
      - /pgdata:/var/lib/postgresql@15/data

  # Frontend: React Application
  frontend:
    container_name: frontend
    build: ./frontend_service
    ports:
      - "3000:3000"
    depends_on:
      - authentication-service

