server:
  port: 8080

logging:
  level:
    org: info

spring:
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: none
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/catalogue
  flyway:
    baseline-on-migrate: true
    enabled: true

app:
  cors:
    allowed-origins: http://localhost:3000